version: '3.8'

services:
  postgres:
    image: postgres:13.15
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    command: ["start-dev", "--import-realm"]
    ports:
      - "8082:8080"
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_DB_URL: "jdbc:postgresql://postgres:5432/profile_db"
      KC_REALM_NAME: SucProfile
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./config/keycloak/import/realm.json:/opt/keycloak/data/import/realm.json:ro
