
spring:
  application:
    name: SucculentumProfile
  datasource:
    url: jdbc:postgresql://postgres:5432/profile_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/SucProfile
jwt:
  auth:
    converter:
      resource-id: authenticationClientId

