<!DOCTYPE html>
<html>
<head>
    <title>Succulentum</title>
</head>

<body>
    <h1>This is the Succulentum main page. Зарегестрируйтесь чтобы попасть в коллекцию</h1>

    <hr>
    <form action="register" method="get">
        <input type="submit" value="К регистрации...">
    </form>

    <hr>
    <h3>Go to collection</h3>
    <form action="collection" method="get">
        <input type="submit" value="Моя коллекция">
    </form>

</body>
</html>